### ISSUE TITLE
possibility to configure the nodeSelector for the resources in the "cert-manager" namespace

### ISSUE THREAD

**Issue by ocpvkb** [openshift/cert-manager-operator#184]
The Operator (Pod) instantiates several pods in the (by RedHat hard-coded) namespace "cert-manager". 
(which will be also created by the Operator Pod)
We need to schedule the resources in the "cert-manager" namespace, which are created and managed by the operator, on nodes of type/role "infra".
According to the CRD, the deployments of resources can be adjusted using the CR “Cert Manager”.
However, this is limited to ENV, labels, request+limits and Args of the containers.
See: https://github.com/openshift/cert-manager-operator/blob/master/pkg/controller/deployment/deployment_overrides.go
Please add the possibility to configure the nodeSelector for the resources in the "cert-manager" namespace.

**Comment by WAR-S** [comment]
+, i want to schedule 3 components with toleration/nodeSelector like this:
  unsupportedConfigOverrides:
    cainjector:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/infra
          operator: Exists
        - effect: NoExecute
          key: node-role.kubernetes.io/infra
          operator: Exists
    controller:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/infra
          operator: Exists
        - effect: NoExecute
          key: node-role.kubernetes.io/infra
          operator: Exists
    webhook:
      nodeSelector:
        node-role.kubernetes.io/infra: ''
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/infra
          operator: Exists
        - effect: NoExecute
          key: node-role.kubernetes.io/infra
          operator: Exists
I want to do this, without label/annotate namespace kind;

@ocpvkb, tell me, I understood your idea correctly?

**Comment by ocpvkb** [comment]
Hello @WAR-S ,
thank you for your answer.
Your suggestion could be a possible solution (besides setting the nodeSelector for the entire "cert-manager" namespace).

The keys “nodeSelector” and “tolerations” should then also be configurable independently of each other.

Whether this configuration is now correctly placed under the item "unsupportedConfigOverrides" can be debated, since "nodeSelector" and "olerations" certainly represent k8s-compliant definitions; far from "unsupported"....
When I look at the possibilities of the operator, "overrideArgs" may be "better" suited.

https://github.com/openshift/cert-manager-operator/blob/master/pkg/controller/deployment/deployment_overrides.go
https://github.com/openshift/cert-manager-operator/blob/master/deploy/examples/cluster-cert-manager-overrides.yaml

**Comment by ocpvkb** [comment]
But yes, you understood my idea correctly.

**Comment by raelga** [comment]
Our team also needs this feature, having the possibility to define tolerations for multi-arch nodes.

/reopen

**Comment by lunarwhite** [comment]
Hi all, this feature has been added into cert-manager-operator v1.15.0, which is planned for release later this month.

**Comment by swghosh** [comment]
^ this is being tracked as a part of next release in https://issues.redhat.com/browse/CM-356.
