### ISSUE TITLE
Integrate cert-manager-operator with OCP "Route" the same way it is done for "Ingress"

### ISSUE THREAD

**Issue by titou10titou10** [openshift/cert-manager-operator#60]
This is a feature request

Currently, this operator only automatically manages annotations in`Ingress`to handle`Certificates`

As this operator specifically targets OpenShift, it should manage`Certificates`required by secured`Route`the same way

As for`Ingress`, this should be done by adding annotations in the `Route`requesting a`Certificate`. 
For`Ingress`,the resulting certificate is stored in a`Secret` and referenced by the`Ingress`. 
As it is not possible to manager certificates outside the `Route`manifest (eg in`Secrets` ), the`Route`manifest should be updated with the generated`Certificate`

**Comment by slaskawi** [comment]
Thanks for the report, @titou10titou10 !

Yes, this is already on our roadmap: https://issues.redhat.com/projects/CM/issues/CM-16

As you already noticed, Routes use TLS certificates burned directly into their specs (not referenced as Secrets). So far the OpenShift Networking Team was refusing using Secrets as it makes the attack surface larger (if anyone takes over the Router, he will have permissions to read all Secrets in the cluster). We will need to agree on what is the proper approach for the longer term.

**Comment by yrro** [comment]
https://github.com/redhat-cop/cert-utils-operator#populating-route-certificates may be of use here - it will watch a secret and apply the certificate, private key, etc. to a route automatically.

**Comment by QuingKhaos** [comment]
Since end of May, the [cert-manager/openshift-routes](https://github.com/cert-manager/openshift-routes) project exists, which solves this problem. IMHO the operator should include a deployment of this project.

`cert-manager/openshift-routes` creates a `CertificateRequest` CR and injects the resulting certificate/private key from the certificate request directly into the annotated `Route` without ever storing it in a secret and also handles renewal like you're used to it from annotating `Ingress` resources.

**Comment by ctrought** [comment]
If OpenShift the `openshift-controller-manager` watches `Ingress` objects and creates a `Route` automatically.

https://docs.openshift.com/container-platform/4.10/networking/routes/route-configuration.html#nw-ingress-creating-a-route-via-an-ingress_route-configuration

The secret configured in the Ingress is used for the `Route`, this secret can be managed by Certmanager so when its create/renewed the `Route` object is automatically updated with the new certificate from that secret. So it is already possible to manage certificates for an OpenShift Route with cert-manager, we do this with the upstream https://github.com/cert-manager/cert-manager install of cert-manager. Of course one of the caveats is you've got to configure it via Ingress so there is an extra object but it works and works pretty well.

**Comment by QuingKhaos** [comment]
@ctrought yes and no. The `Ingress` workaround and injecting by `cert-utils-operator` are well known, but not the solution. Both cases still create a `Secret` for the certificate.

The wanted use case is to directly annotate the `Route` and get the cert material injected in the `Route` spec, with no lingering secrets. See

> So far the OpenShift Networking Team was refusing using Secrets as it makes the attack surface larger (if anyone takes over the Router, he will have permissions to read all Secrets in the cluster).

This is were [cert-manager/openshift-routes](https://github.com/cert-manager/openshift-routes) project comes in.

> Why is This a Separate Project?
>
> We do not wish to support non Kubernetes (or kubernetes-sigs) APIs in cert-manager core. This adds a large maintenance burden, and it's hard for us to e2e test everyone's CRDs. **However, OpenShift is widely used, so it makes sense to have some support for it in the cert-manager ecosystem.**

So the user story is: As an OCP Operator/DevOps/<insert similar job title> I want to annotate Routes with cert-manager annotations like Ingress and the Route gets populated with the cert material when this cert-manager-operator is installed in the cluster.
