### ISSUE TITLE
Add ServiceMonitor by default

### ISSUE THREAD

**Issue by diskmanti** [openshift/cert-manager-operator#66]
Right now cert-manger support monitoring through a ServiceMonitor.

Since the operator by default is installed in the openshift namespaces, creation of user defined ServiceMonitors is not support.

Can the default ServiceMonitor be created durin the operator installation process?

Thank you

**Comment by lunarwhite** [comment]
This doc might be helpful: https://docs.openshift.com/container-platform/4.14/security/cert_manager_operator/cert-manager-monitoring.html
