### ISSUE TITLE
Consumption and application of Cluster Proxy and Additional Trust Bundles

### ISSUE THREAD

**Issue by kenmoini** [openshift/cert-manager-operator#72]
As it is, the cert-manager operator does not inject the needed cluster proxy and custom root CA configuration into the running Pods.

You can inject the environmental variables for `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` into the operator Subscription, which will apply them to the controller, but the controller does not pass them to the Deployments that are created by the CertManager instance.

This is useful in case a cluster is behind an outbound proxy and needs to communicate with an ACME server on the internet, such as the Sectigo OV ACME server.

**Comment by xingxingxia** [comment]
Being implemented by https://github.com/openshift/cert-manager-operator/pull/103, yet to merge, which has been pre-merge verified now: https://github.com/openshift/cert-manager-operator/pull/103#issuecomment-1433066580
