### ISSUE TITLE
Why is cert-manager a cluster operator?

### ISSUE THREAD

**Issue by gnunn1** [openshift/cert-manager-operator#73]
For some reason cert-manager has registered itself as a cluster operator in OpenShift with a version that is (1.7.1) then is different then every other cluster operator (OpenShift version i.e. 4.10.12). Can we either remove cert-manager as a cluster operator or alternatively adjust it's version and lifecycle to match all of the other cluster operators.

This behavior is needlessly confusing for customers particularly for something that is Tech Preview. I have opened an issue in JIRA as well (https://issues.redhat.com/browse/CM-35) but I'm not sure this JIRA project is used?

![cert-manager-cluster-operator](https://user-images.githubusercontent.com/9358238/179292411-43ae097a-9c18-4ccf-a478-3458890ddf14.png)

**Comment by yrro** [comment]
Looks like this was fixed in 1.10.2

https://docs.openshift.com/container-platform/4.12/security/cert_manager_operator/cert-manager-operator-release-notes.html

**Comment by swghosh** [comment]
This operator is no more an OpenShift cluster operator. We have had fixed this behaviour from [cert-manager Operator for Red Hat OpenShift 1.10.2](https://docs.openshift.com/container-platform/latest/security/cert_manager_operator/cert-manager-operator-release-notes.html) and above.

**Comment by yrro** [comment]
I've got `cert-manager-operator.v1.12.1` installed, but the cluster operator object is still present:

```
$ oc get co/cert-manager
NAME           VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
cert-manager   1.7.1     True        False         False      29d     
```

Is this object supposed to have been deleted automatically? If not, can I delete it by hand?
