### ISSUE TITLE
Does cert-manager handle the api and *.apps certificates?

### ISSUE THREAD

**Issue by pbrooksbcbsnc** [openshift/cert-manager-operator#74]
Howdy cert-manager people,

I'm trying to understand the scope of cert-manager: Does cert-manager currently handle (or, is cert-manager envisioned to handle) o custom certificates used with an OpenShift cluster's api and *.apps endpoints?

Specifically, does (or could?) cert-manager do what these procedures describe:

- https://docs.openshift.com/container-platform/4.10/security/certificates/api-server.html
- https://docs.openshift.com/container-platform/4.10/security/certificates/replacing-default-ingress-certificate.html

Any education appreciated -- Thanks!
patrick

**Comment by yrro** [comment]
It _should_ be able to do that. Those certificates aren't special--as long as they exist (and are referred to by the apiserver and default ingress controller configuration custom resources) then it should work.

(Appropriate disclaimer: I'm only a user of OpenShift, so take that with the usual grain of salt!)

**Comment by QuingKhaos** [comment]
@pbrooksbcbsnc not an issue for the operator though, but for cert-manager itself.

Anyways, cert-manager just creates appropriate tls secrets, so yes you can use cert-manager for managing those. We use cert-manager in every cluster to manage API and Ingress certificates.
