### ISSUE TITLE
Install fails if there are existing CRs

### ISSUE THREAD

**Issue by davidkarlsen** [openshift/cert-manager-operator#75]
operator install will fail with:

```
error validating existing CRs against new CRD's schema for "clusterissuers.cert-manager.io": error listing resources in GroupVersionResource schema.GroupVersionResource{Group:"cert-manager.io", Version:"v1alpha2", Resource:"clusterissuers"}: conversion webhook for cert-manager.io/v1, Kind=ClusterIssuer failed: Post "https://cert-manager-webhook.cert-manager.svc:443/convert?timeout=30s": service "cert-manager-webhook" not found
```

if there are existing CRs in the cluster.

**Comment by QuingKhaos** [comment]
It seems you had a previous cert-manager installation and thus existing CR for v1alpha2 which were deprecated in cert-manager v1.4 and removed in v1.7 and missed the release notes to convert your CRs before upgrading: https://cert-manager.io/docs/release-notes/release-notes-1.7#upgrading-with-server-side-apply
