### ISSUE TITLE
can we use configure to be an intermediate to our organization CA ( we use AD ad CA ) ?

### ISSUE THREAD

**Issue by SOUIHEL-ayoub** [openshift/cert-manager-operator#79]

**Comment by abdennour** [comment]
Hello guys! this is a valid case. How to configure Cert-manager operator with CA bundle certificate 
already the configmap with label (config.openshift.io/inject-trusted-cabundle: true) is created.
What's next ?
Is it ok to mutate the Pod/deployment with volumeMounts ?!

**Comment by abdennour** [comment]
lifecycle /stale

**Comment by swghosh** [comment]
@abdennour Are you looking for ways to inject the Azure CA certificate onto pods of different workloads that are being run (so workloads can trust that relevant certificates came from a trusted source)
_(or)_
you are looking for steps to create an Issuer of type CA that has the ability to create new certificates out of the said CA certificate?
